### ISSUE TITLE
tskserver and the thundering herd

### ISSUE THREAD

**Issue by bcov77** [TACC/launcher#55]
Hi,

I've noticed that sometimes when running single-cpu jobs on lots of nodes, the `tskserver` gets overwhelmed by `ncat` requests. The result is that some of these `ncat` requests hang indefinitely causing the job to run into its walltime. I managed to do this on lonestar5 with only 3 nodes, but it can probably be replicated elsewhere.

Anyways, I have a crude fix, but I figured I'd make an issue rather than a pull request as there might be a cleaner way to fix the issue.

Adding this line at the top of `launcher` fixed the problem for me:
```bash
sleep $[ ( $RANDOM % 50 )  + 1 ]s  # random 50s sleep
```

**Comment by siliu-tacc** [comment]
I can update it in the next release.
Thx

**Comment by siliu-tacc** [comment]
50s is too long

sleep $[ ( $RANDOM % 24 )  + 1 ]s
