### ISSUE TITLE
Allow launcher to launch multi-core jobs such as openMP jobs.

### ISSUE THREAD

**Issue by armando-fandango** [TACC/launcher#6]
Currently launcher only schedules one job on a core. How can I make launcher launch a job at multiple cores such as openmp jobs.

**Comment by lwilson** [comment]
You can change the total number of processes per node by setting LAUNCHER_PPN. So if you have a 24-core node and want to run 3 OpenMP applications with 8 threads each, just do the following:

`export OMP_NUM_THREADS=8`
`export LAUNCHER_PPN=3`
`$LAUNCHER_DIR/paramrun`

Also, if you explicitly export a value for LAUNCHER_PPN, it will honor your settings even if you have scheduler integration enabled.

**Comment by zhenzuo2** [comment]
I tried to add 

export LAUNCHER_PPN=1

But I checked the log it still runs multiple jobs together. Can I limit the number of jobs running at the same time?

**Comment by zhenzuo2** [comment]
#!/bin/bash
#
# Simple SLURM script for submitting multiple serial
# jobs (e.g. parametric studies) using a script wrapper
# to launch the jobs.
#
# To use, build the launcher executable and your
# serial application(s) and place them in your WORKDIR
# directory.  Then, edit the CONTROL_FILE to specify
# each executable per process.
#-------------------------------------------------------
#-------------------------------------------------------
#
# <------ Setup Parameters ------>
#
#SBATCH -J Parametric
#SBATCH -n 96
#SBATCH -N 2
#SBATCH -p hadoop
#SBATCH -o Parametric.o%j
#SBATCH -t 48:00:00
#  <------ Account String ----->
# <--- (Use this ONLY if you have MULTIPLE accounts) --->
##SBATCH -A
#------------------------------------------------------

module load launcher
export LAUNCHER_RMI=SLURM
export LAUNCHER_JOB_FILE=/work/05978/zzuo/mysharedirectory/eqtl/code/job_chr_1.sh
export LAUNCHER_WORKDIR=/work/05978/zzuo/mysharedirectory/eqtl/processed/
export LAUNCHER_SCHED=interleaved
export LAUNCHER_PPN=1
$LAUNCHER_DIR/paramrun






/opt/apps/launcher/launcher-3.1/paramrun: line 171: [: -eq: unary operator expected
Launcher: Setup complete.

------------- SUMMARY ---------------
   Number of hosts:    2
   Working directory:  /work/05978/zzuo/mysharedirectory/eqtl/processed/
   Processes per host: 48
   Total processes:    96
   Total jobs:         50
   Scheduling method:  interleaved
/opt/apps/launcher/launcher-3.1/paramrun: line 211: [: -eq: unary operator expected

-------------------------------------
Launcher: Starting parallel tasks...
Launcher: Task 1 running job 2 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$Launcher: Task 7 running job 8 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$Launcher: Task 6 running job 7 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$Launcher: Task 5 running job 6 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$Launcher: Task 2 running job 3 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$Launcher: Task 19 running job 20 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WG$Launcher: Task 13 running job 14 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WG$Launcher: Task 8 running job 9 on c252-110.wrangler.tacc.utexas.edu (module load biocontainers; module load fastqtl/ctr-v2.184dfsg-5-deb_cv1; fastQTL -V merge2.WGS-$L
